In [1]:
import pandas as pd
df = pd.read_excel('../data/appstoregames.xlsx')
print(df.shape)
df.head()

(17007, 16)

,App URL,App ID,Name,Subtitle,Icon URL,Average User Rating,User Rating Count,Price per App (USD),Description,Developer,Age Rating,Languages,Size in Bytes,Primary Genre,Genres,Release Date
0,https://apps.apple.com/us/app/sudoku/id284921427,284921427,Sudoku,NaN,https://is2-ssl.mzstatic.com/image/thumb/Purpl...,4.0,3553.0,2.99,"Join over 21,000,000 of our fans and download ...",Mighty Mighty Good Games,4+,"DA, NL, EN, FI, FR, DE, IT, JA, KO, NB, PL, PT...",15853568.0,Games,"Games, Strategy, Puzzle",2008-07-11
1,https://apps.apple.com/us/app/reversi/id284926400,284926400,Reversi,NaN,https://is4-ssl.mzstatic.com/image/thumb/Purpl...,3.5,284.0,1.99,"The classic game of Reversi, also known as Oth...",Kiss The Machine,4+,EN,12328960.0,Games,"Games, Strategy, Board",2008-07-11
2,https://apps.apple.com/us/app/morocco/id284946595,284946595,Morocco,NaN,https://is5-ssl.mzstatic.com/image/thumb/Purpl...,3.0,8376.0,0.00,Play the classic strategy game Othello (also k...,Bayou Games,4+,EN,674816.0,Games,"Games, Board, Strategy",2008-07-11
3,https://apps.apple.com/us/app/sudoku-free/id28...,285755462,Sudoku (Free),NaN,https://is3-ssl.mzstatic.com/image/thumb/Purpl...,3.5,190394.0,0.00,"Top 100 free app for over a year.\nRated ""Best...",Mighty Mighty Good Games,4+,"DA, NL, EN, FI, FR, DE, IT, JA, KO, NB, PL, PT...",21552128.0,Games,"Games, Strategy, Puzzle",2008-07-23
4,https://apps.apple.com/us/app/senet-deluxe/id2...,285831220,Senet Deluxe,NaN,https://is1-ssl.mzstatic.com/image/thumb/Purpl...,3.5,28.0,2.99,"""Senet Deluxe - The Ancient Game of Life and A...",RoGame Software,4+,"DA, NL, EN, FR, DE, EL, IT, JA, KO, NO, PT, RU...",34689024.0,Games,"Games, Strategy, Board, Education",2008-07-18

In [2]:
print(df.columns.tolist())

['App URL', 'App ID', 'Name', 'Subtitle', 'Icon URL', 'Average User Rating', 'User Rating Count', 'Price per App (USD)', 'Description', 'Developer', 'Age Rating', 'Languages', 'Size in Bytes', 'Primary Genre', 'Genres', 'Release Date']

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17007 entries, 0 to 17006
Data columns (total 16 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   App URL              17007 non-null  object
 1   App ID               17007 non-null  int64
 2   Name                 17006 non-null  object
 3   Subtitle             5257 non-null   object
 4   Icon URL             17007 non-null  object
 5   Average User Rating  7561 non-null   float64
 6   User Rating Count    7561 non-null   float64
 7   Price per App (USD)  17007 non-null  float64
 8   Description          16990 non-null  object
 9   Developer            17007 non-null  object
 10  Age Rating           17007 non-null  object
 11  Languages            17007 non-null  object
 12  Size in Bytes        17006 non-null  float64
 13  Primary Genre        17007 non-null  object
 14  Genres               17007 non-null  object
 15  Release Date         17007 non-null  datetime64[ns]
dtypes: datetime64[ns](1), float64(4), int64(1), object(10)
memory usage: 2.1+ MB

In [4]:
df.describe()

,App ID,Average User Rating,User Rating Count,Price per App (USD),Size in Bytes,Release Date
count,1.700700e+04,7561.000000,7.561000e+03,17007.000000,1.700600e+04,17007
mean,1.059614e+09,4.060905,3.306531e+03,0.812271,1.157064e+08,2016-03-04 18:55:41.541717760
min,2.849214e+08,1.000000,5.000000e+00,0.000000,5.132800e+04,2008-07-11 00:00:00
25%,8.996543e+08,3.500000,1.200000e+01,0.000000,2.295014e+07,2014-09-23 00:00:00
50%,1.112286e+09,4.500000,4.600000e+01,0.000000,5.676895e+07,2016-07-09 00:00:00
75%,1.286983e+09,4.500000,3.090000e+02,0.000000,1.330271e+08,2017-12-07 00:00:00
max,1.475077e+09,5.000000,3.032734e+06,179.990000,4.005591e+09,2019-10-26 00:00:00
std,2.999676e+08,0.751428,4.232256e+04,7.830260,2.036477e+08,NaN

In [5]:
duplicate_count = df.duplicated(subset=['App ID']).sum()
print(f"Số lượng game bị trùng lặp: {duplicate_count}")

Số lượng game bị trùng lặp: 160

In [6]:
if duplicate_count > 0:
    df = df.drop_duplicates(subset=['App ID'], keep='first')
    print("Done!")

Done!

In [7]:
df.isnull().sum()

App URL                    0
App ID                     0
Name                       1
Subtitle               11638
Icon URL                   0
Average User Rating     9359
User Rating Count       9359
Price per App (USD)        0
Description               17
Developer                  0
Age Rating                 0
Languages                  0
Size in Bytes              1
Primary Genre              0
Genres                     0
Release Date               0
dtype: int64

In [8]:
import numpy as np
#1. Xóa cột ko cần thiết
columns_to_drop = ['App URL', 'Icon URL', 'Subtitle']
df = df.drop(columns=columns_to_drop)

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 16847 entries, 0 to 17006
Data columns (total 13 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   App ID               16847 non-null  int64
 1   Name                 16846 non-null  object
 2   Average User Rating  7488 non-null   float64
 3   User Rating Count    7488 non-null   float64
 4   Price per App (USD)  16847 non-null  float64
 5   Description          16830 non-null  object
 6   Developer            16847 non-null  object
 7   Age Rating           16847 non-null  object
 8   Languages            16847 non-null  object
 9   Size in Bytes        16846 non-null  float64
 10  Primary Genre        16847 non-null  object
 11  Genres               16847 non-null  object
 12  Release Date         16847 non-null  datetime64[ns]
dtypes: datetime64[ns](1), float64(4), int64(1), object(7)
memory usage: 1.8+ MB

In [10]:
#2. Xử lý missing values
df = df.dropna(subset=['Average User Rating', 'User Rating Count'])

In [11]:
df = df.dropna(subset=['Name', 'Size in Bytes', 'Description'])

In [12]:
df['Size in MB'] = round(df['Size in Bytes'] / (1024 * 1024), 2)

In [13]:
df = df.drop(columns=['Size in Bytes'])

In [14]:
#Phân loại game miễn phí/ trả phí
df['Is Free'] = np.where(df['Price per App (USD)'] == 0, 'Free', 'Paid')

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7482 entries, 0 to 16993
Data columns (total 14 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   App ID               7482 non-null   int64
 1   Name                 7482 non-null   object
 2   Average User Rating  7482 non-null   float64
 3   User Rating Count    7482 non-null   float64
 4   Price per App (USD)  7482 non-null   float64
 5   Description          7482 non-null   object
 6   Developer            7482 non-null   object
 7   Age Rating           7482 non-null   object
 8   Languages            7482 non-null   object
 9   Primary Genre        7482 non-null   object
 10  Genres               7482 non-null   object
 11  Release Date         7482 non-null   datetime64[ns]
 12  Size in MB           7482 non-null   float64
 13  Is Free              7482 non-null   object
dtypes: datetime64[ns](1), float64(4), int64(1), object(8)
memory usage: 876.8+ KB

In [16]:
df.isnull().sum()

App ID                 0
Name                   0
Average User Rating    0
User Rating Count      0
Price per App (USD)    0
Description            0
Developer              0
Age Rating             0
Languages              0
Primary Genre          0
Genres                 0
Release Date           0
Size in MB             0
Is Free                0
dtype: int64

In [17]:
df.shape

(7482, 14)

In [ ]:
from sqlalchemy import create_engine
engine = create_engine('postgresql://postgres:your_password_here@localhost:5432/mobile_game_db')

df.to_sql('mobile_games', engine, if_exists='replace', index=False)
print("Done!")

Done!